In [11]:
from sklearn.datasets import load_iris
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
import numpy as np
iris = load_iris()

In [2]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [3]:
from sklearn.model_selection import cross_val_score

In [13]:
score_1 = cross_val_score(LogisticRegression(),iris.data,iris.target,cv=3)
print(score_1)

[0.98 0.96 0.98]


C:\Users\chaks\AppData\Roaming\Python\Python312\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [14]:
np.average(score_1)

np.float64(0.9733333333333333)

In [35]:
score_2 = cross_val_score(SVC(gamma=5),iris.data,iris.target,cv=3)
print(score_2)

[1.   0.96 0.96]


In [36]:
np.average(score_2)

np.float64(0.9733333333333333)

In [37]:
score_3 = cross_val_score(RandomForestClassifier(n_estimators=11),iris.data,iris.target,cv=3)
print(score_3)

[0.98 0.94 0.96]


In [38]:
np.average(score_3)

np.float64(0.96)

In [43]:
score_4 = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target,cv=3)
score_4

array([0.98, 0.92, 0.98])

In [44]:
np.average(score_4)

np.float64(0.96)

Best score so far is from SVM: 0.97344771241830064